version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_USER=${JENKINS_USER}
      - JENKINS_PASS=${JENKINS_PASS}
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/configuration.yaml:/var/jenkins_home/configuration.yaml

volumes:
  jenkins_home:
